# Generated by Django 2.1.5 on 2019-01-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=5000)),
                ('images', models.TextField(default='', max_length=50000)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Pic1',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('pid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('similar_rate', models.TextField(default='', max_length=1000000000)),
            ],
            options={
                'ordering': ('pid',),
            },
        ),
    ]
